"""Add generation_logs column to campaigns table

Revision ID: 8015e569c775
Revises: 
Create Date: 2025-11-15 23:37:09.129707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8015e569c775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add generation_logs column to campaigns table
    op.add_column('campaigns', sa.Column('generation_logs', postgresql.JSONB(), nullable=True, server_default='[]'))

    # Drop test_table if it exists
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate test_table
    op.create_table('test_table',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )

    # Remove generation_logs column from campaigns table
    op.drop_column('campaigns', 'generation_logs')
    # ### end Alembic commands ###


